// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userinfo

import (
	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// newUserInfoServiceInterfaceMock creates a new instance of userInfoServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newUserInfoServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *userInfoServiceInterfaceMock {
	mock := &userInfoServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// userInfoServiceInterfaceMock is an autogenerated mock type for the userInfoServiceInterface type
type userInfoServiceInterfaceMock struct {
	mock.Mock
}

type userInfoServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *userInfoServiceInterfaceMock) EXPECT() *userInfoServiceInterfaceMock_Expecter {
	return &userInfoServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type userInfoServiceInterfaceMock
func (_m *userInfoServiceInterfaceMock) GetUserInfo(accessToken string) (*UserInfoResponse, *serviceerror.ServiceError) {
	ret := _m.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *UserInfoResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(string) (*UserInfoResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *UserInfoResponse); ok {
		r0 = returnFunc(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserInfoResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// userInfoServiceInterfaceMock_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type userInfoServiceInterfaceMock_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - accessToken string
func (_e *userInfoServiceInterfaceMock_Expecter) GetUserInfo(accessToken interface{}) *userInfoServiceInterfaceMock_GetUserInfo_Call {
	return &userInfoServiceInterfaceMock_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", accessToken)}
}

func (_c *userInfoServiceInterfaceMock_GetUserInfo_Call) Run(run func(accessToken string)) *userInfoServiceInterfaceMock_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *userInfoServiceInterfaceMock_GetUserInfo_Call) Return(response *UserInfoResponse, serviceError *serviceerror.ServiceError) *userInfoServiceInterfaceMock_GetUserInfo_Call {
	_c.Call.Return(response, serviceError)
	return _c
}

func (_c *userInfoServiceInterfaceMock_GetUserInfo_Call) RunAndReturn(run func(accessToken string) (*UserInfoResponse, *serviceerror.ServiceError)) *userInfoServiceInterfaceMock_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}
